/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PoDMPaymentProtocol {
  export type RecurringAllowanceStruct = {
    maxAmountPerPeriod: BigNumberish;
    periodInSeconds: BigNumberish;
    lastRenewalAt: BigNumberish;
    active: boolean;
  };

  export type RecurringAllowanceStructOutput = [
    maxAmountPerPeriod: bigint,
    periodInSeconds: bigint,
    lastRenewalAt: bigint,
    active: boolean
  ] & {
    maxAmountPerPeriod: bigint;
    periodInSeconds: bigint;
    lastRenewalAt: bigint;
    active: boolean;
  };
}

export interface PoDMPaymentProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowances"
      | "approveRecurringSubscription"
      | "getAllowance"
      | "owner"
      | "pause"
      | "paused"
      | "payPPV"
      | "paySubscription"
      | "payTip"
      | "platformFeeBps"
      | "platformTreasury"
      | "processPayout"
      | "processRenewal"
      | "renounceOwnership"
      | "revokeRecurringSubscription"
      | "setPlatformFeeBps"
      | "setPlatformTreasury"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "OwnershipTransferred"
      | "PPVPaid"
      | "Paused"
      | "PayoutCompleted"
      | "SubscriptionApproved"
      | "SubscriptionPaid"
      | "SubscriptionRenewed"
      | "SubscriptionRevoked"
      | "TipPaid"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRecurringSubscription",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payPPV",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paySubscription",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payTip",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processPayout",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processRenewal",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRecurringSubscription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "allowances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveRecurringSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payPPV", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paySubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payTip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRecurringSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PPVPaidEvent {
  export type InputTuple = [
    fan: AddressLike,
    creator: AddressLike,
    token: AddressLike,
    totalAmount: BigNumberish,
    contentIdHash: BytesLike,
    platformFee: BigNumberish,
    creatorAmount: BigNumberish
  ];
  export type OutputTuple = [
    fan: string,
    creator: string,
    token: string,
    totalAmount: bigint,
    contentIdHash: string,
    platformFee: bigint,
    creatorAmount: bigint
  ];
  export interface OutputObject {
    fan: string;
    creator: string;
    token: string;
    totalAmount: bigint;
    contentIdHash: string;
    platformFee: bigint;
    creatorAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutCompletedEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionApprovedEvent {
  export type InputTuple = [
    fan: AddressLike,
    creator: AddressLike,
    maxAmountPerPeriod: BigNumberish,
    periodInSeconds: BigNumberish
  ];
  export type OutputTuple = [
    fan: string,
    creator: string,
    maxAmountPerPeriod: bigint,
    periodInSeconds: bigint
  ];
  export interface OutputObject {
    fan: string;
    creator: string;
    maxAmountPerPeriod: bigint;
    periodInSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionPaidEvent {
  export type InputTuple = [
    fan: AddressLike,
    creator: AddressLike,
    token: AddressLike,
    totalAmount: BigNumberish,
    tierIdHash: BytesLike,
    platformFee: BigNumberish,
    creatorAmount: BigNumberish
  ];
  export type OutputTuple = [
    fan: string,
    creator: string,
    token: string,
    totalAmount: bigint,
    tierIdHash: string,
    platformFee: bigint,
    creatorAmount: bigint
  ];
  export interface OutputObject {
    fan: string;
    creator: string;
    token: string;
    totalAmount: bigint;
    tierIdHash: string;
    platformFee: bigint;
    creatorAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRenewedEvent {
  export type InputTuple = [
    fan: AddressLike,
    creator: AddressLike,
    amount: BigNumberish,
    renewedAt: BigNumberish
  ];
  export type OutputTuple = [
    fan: string,
    creator: string,
    amount: bigint,
    renewedAt: bigint
  ];
  export interface OutputObject {
    fan: string;
    creator: string;
    amount: bigint;
    renewedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRevokedEvent {
  export type InputTuple = [fan: AddressLike, creator: AddressLike];
  export type OutputTuple = [fan: string, creator: string];
  export interface OutputObject {
    fan: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipPaidEvent {
  export type InputTuple = [
    fan: AddressLike,
    creator: AddressLike,
    token: AddressLike,
    totalAmount: BigNumberish,
    platformFee: BigNumberish,
    creatorAmount: BigNumberish
  ];
  export type OutputTuple = [
    fan: string,
    creator: string,
    token: string,
    totalAmount: bigint,
    platformFee: bigint,
    creatorAmount: bigint
  ];
  export interface OutputObject {
    fan: string;
    creator: string;
    token: string;
    totalAmount: bigint;
    platformFee: bigint;
    creatorAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoDMPaymentProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): PoDMPaymentProtocol;
  waitForDeployment(): Promise<this>;

  interface: PoDMPaymentProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        maxAmountPerPeriod: bigint;
        periodInSeconds: bigint;
        lastRenewalAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  approveRecurringSubscription: TypedContractMethod<
    [
      creator: AddressLike,
      maxAmountPerPeriod: BigNumberish,
      periodInSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAllowance: TypedContractMethod<
    [fan: AddressLike, creator: AddressLike],
    [PoDMPaymentProtocol.RecurringAllowanceStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payPPV: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      creator: AddressLike,
      amount: BigNumberish,
      contentIdHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  paySubscription: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      creator: AddressLike,
      amount: BigNumberish,
      tierIdHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  payTip: TypedContractMethod<
    [tokenAddress: AddressLike, creator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  processPayout: TypedContractMethod<
    [tokenAddress: AddressLike, creator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  processRenewal: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      fan: AddressLike,
      creator: AddressLike,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeRecurringSubscription: TypedContractMethod<
    [creator: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFeeBps: TypedContractMethod<
    [_newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        maxAmountPerPeriod: bigint;
        periodInSeconds: bigint;
        lastRenewalAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveRecurringSubscription"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      maxAmountPerPeriod: BigNumberish,
      periodInSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllowance"
  ): TypedContractMethod<
    [fan: AddressLike, creator: AddressLike],
    [PoDMPaymentProtocol.RecurringAllowanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payPPV"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      creator: AddressLike,
      amount: BigNumberish,
      contentIdHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "paySubscription"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      creator: AddressLike,
      amount: BigNumberish,
      tierIdHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payTip"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, creator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayout"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, creator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processRenewal"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      fan: AddressLike,
      creator: AddressLike,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRecurringSubscription"
  ): TypedContractMethod<[creator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeBps"
  ): TypedContractMethod<[_newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PPVPaid"
  ): TypedContractEvent<
    PPVPaidEvent.InputTuple,
    PPVPaidEvent.OutputTuple,
    PPVPaidEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutCompleted"
  ): TypedContractEvent<
    PayoutCompletedEvent.InputTuple,
    PayoutCompletedEvent.OutputTuple,
    PayoutCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionApproved"
  ): TypedContractEvent<
    SubscriptionApprovedEvent.InputTuple,
    SubscriptionApprovedEvent.OutputTuple,
    SubscriptionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionPaid"
  ): TypedContractEvent<
    SubscriptionPaidEvent.InputTuple,
    SubscriptionPaidEvent.OutputTuple,
    SubscriptionPaidEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRenewed"
  ): TypedContractEvent<
    SubscriptionRenewedEvent.InputTuple,
    SubscriptionRenewedEvent.OutputTuple,
    SubscriptionRenewedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRevoked"
  ): TypedContractEvent<
    SubscriptionRevokedEvent.InputTuple,
    SubscriptionRevokedEvent.OutputTuple,
    SubscriptionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TipPaid"
  ): TypedContractEvent<
    TipPaidEvent.InputTuple,
    TipPaidEvent.OutputTuple,
    TipPaidEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PPVPaid(address,address,address,uint256,bytes32,uint256,uint256)": TypedContractEvent<
      PPVPaidEvent.InputTuple,
      PPVPaidEvent.OutputTuple,
      PPVPaidEvent.OutputObject
    >;
    PPVPaid: TypedContractEvent<
      PPVPaidEvent.InputTuple,
      PPVPaidEvent.OutputTuple,
      PPVPaidEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PayoutCompleted(address,uint256)": TypedContractEvent<
      PayoutCompletedEvent.InputTuple,
      PayoutCompletedEvent.OutputTuple,
      PayoutCompletedEvent.OutputObject
    >;
    PayoutCompleted: TypedContractEvent<
      PayoutCompletedEvent.InputTuple,
      PayoutCompletedEvent.OutputTuple,
      PayoutCompletedEvent.OutputObject
    >;

    "SubscriptionApproved(address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionApprovedEvent.InputTuple,
      SubscriptionApprovedEvent.OutputTuple,
      SubscriptionApprovedEvent.OutputObject
    >;
    SubscriptionApproved: TypedContractEvent<
      SubscriptionApprovedEvent.InputTuple,
      SubscriptionApprovedEvent.OutputTuple,
      SubscriptionApprovedEvent.OutputObject
    >;

    "SubscriptionPaid(address,address,address,uint256,bytes32,uint256,uint256)": TypedContractEvent<
      SubscriptionPaidEvent.InputTuple,
      SubscriptionPaidEvent.OutputTuple,
      SubscriptionPaidEvent.OutputObject
    >;
    SubscriptionPaid: TypedContractEvent<
      SubscriptionPaidEvent.InputTuple,
      SubscriptionPaidEvent.OutputTuple,
      SubscriptionPaidEvent.OutputObject
    >;

    "SubscriptionRenewed(address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;
    SubscriptionRenewed: TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;

    "SubscriptionRevoked(address,address)": TypedContractEvent<
      SubscriptionRevokedEvent.InputTuple,
      SubscriptionRevokedEvent.OutputTuple,
      SubscriptionRevokedEvent.OutputObject
    >;
    SubscriptionRevoked: TypedContractEvent<
      SubscriptionRevokedEvent.InputTuple,
      SubscriptionRevokedEvent.OutputTuple,
      SubscriptionRevokedEvent.OutputObject
    >;

    "TipPaid(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TipPaidEvent.InputTuple,
      TipPaidEvent.OutputTuple,
      TipPaidEvent.OutputObject
    >;
    TipPaid: TypedContractEvent<
      TipPaidEvent.InputTuple,
      TipPaidEvent.OutputTuple,
      TipPaidEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
