version: '3.8'

services:
  backend:
    build: ./PoDM_project
    ports:
      - "5000:5000"
    env_file:
      - ./PoDM_project/server/.env
    volumes:
      - ./PoDM_project:/app
      - /app/node_modules

  frontend:
    build: ./podm-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./podm-frontend/.env
    volumes:
      - ./podm-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
