// Auto-generated contract configuration and helper module.
// DO NOT EDIT DIRECTLY. Generated by scripts/generateContractConfig.ts

export const PODM_CONTRACT_ABI = [
    "function paySubscription(address,address,uint256,bytes32,address,uint256)",
    "function payTip(address,address,uint256,address,uint256)",
    "function payPPV(address,address,uint256,bytes32,address,uint256)",
    "function processRenewal(bytes32,address,address,address,uint256,address,uint256)",
    "function processPayout(address,address,uint256)"
] as const;

export const ERC20_ABI = [
    "function approve(address spender, uint256 amount) returns (bool)",
    "function allowance(address owner, address spender) view returns (uint256)"
] as const;

export const FUNCTION_SELECTORS = {
    "paySubscription": "0xe87c1a59",
    "payTip": "0x7a02b81c",
    "payPPV": "0x33f2ab62",
    "processRenewal": "0xac6e9fa5",
    "processPayout": "0x32ab19f5"
} as const;

export const ERC20_SELECTORS = {
    "approve": "0x095ea7b3",
    "allowance": "0xdd62ed3e"
} as const;

export const EVENT_TOPICS = {
    "SubscriptionPaid": "0xf0d9472764df1a9312b9f3b7f65cf4bdbdc6e14d2a62ba2bc26a8f6e6aaa4f0f",
    "TipPaid": "0x66a5edbb6d291cfdfe5416d10c7b2ab3945cc677886f0c1402a0cc97b27a401e",
    "PPVPaid": "0x2cf7aa3667273c8a63cbfe97b90efad3c581892c51971a26bca142ada84c8ef3"
} as const;
