import supabase from '../config/supabaseClient';
import { Content } from '@common/types/Content';

/**
 * Creates a new piece of content in the database.
 * @param contentData - The data for the new content.
 * @returns The newly created content object.
 */
export const createContent = async (contentData: Partial<Content>): Promise<Content | null> => {
    const { data, error } = await supabase
        .from('content')
        .insert([contentData])
        .select()
        .single();

    if (error) {
        console.error('Error creating content:', error.message);
        return null;
    }
    return data as Content;
};

/**
 * Counts the total number of content pieces in the database.
 */
export const countAllContent = async (): Promise<number> => {
    const { count, error } = await supabase
        .from('content')
        .select('*', { count: 'exact', head: true });

    if (error) {
        console.error('Error counting content:', error.message);
        return 0;
    }
    return count || 0;
};

/**
 * Finds a single piece of content by its unique ID.
 * @param id - The ID of the content to find.
 * @returns The content object or null if not found.
 */
export const findContentById = async (id: string): Promise<Content | null> => {
    const contentId = parseInt(id, 10);
    if (isNaN(contentId)) {
        console.error(`[Model] findContentById: Invalid non-numeric ID passed: "${id}"`);
        return null;
    }

    console.log(`[Model] findContentById: Querying database for content with id=${contentId}`);

    const { data, error } = await supabase
        .from('content')
        .select('*')
        .eq('id', contentId)
        .single();

    if (error) {
        // A "Not Found" error is expected if the ID doesn't exist, so we don't log it as a critical failure.
        if (error.code !== 'PGRST116') { // PGRST116 = "The result contains 0 rows"
            console.error(`[Model] Database error finding content by ID ${contentId}:`, error.message);
        } else {
            console.log(`[Model] No content found for id=${contentId}.`);
        }
        return null;
    }
    
    console.log(`[Model] Successfully found content for id=${contentId}.`);
    return data as Content;
};

/**
 * Finds multiple pieces of content by an array of their unique IDs.
 * @param ids - An array of content IDs to find.
 * @returns An array of content objects.
 */
export const findContentByIds = async (ids: string[]): Promise<Content[] | null> => {
    if (ids.length === 0) {
        return [];
    }
    const { data, error } = await supabase
        .from('content')
        .select('*')
        .in('id', ids);

    if (error) {
        console.error('Error finding content by IDs:', error.message);
        return null;
    }
    return data as Content[];
};

/**
 * Finds content by its status (e.g., 'published', 'flagged', 'removed').
 * @param status - The status to filter content by.
 */
export const findContentByStatus = async (status: string): Promise<Content[] | null> => {
    const { data, error } = await supabase
        .from('content')
        .select('*')
        .eq('status', status)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error finding content by status:', error.message);
        return null;
    }
    return data as Content[];
};

/**
 * Finds all content created by a specific creator.
 * @param creatorId - The UUID of the creator.
 * @returns An array of content objects.
 */
export const findContentByCreatorId = async (creatorId: string, limit?: number, offset?: number): Promise<Content[] | null> => {
    let query = supabase
        .from('content')
        .select('*')
        .eq('creator_id', creatorId)
        .order('created_at', { ascending: false });

    if (limit !== undefined && offset !== undefined) {
        query = query.range(offset, offset + limit - 1);
    }

    const { data, error } = await query;

    
    if (error) {
        console.error('Error finding content by creator ID:', error.message);
        return null;
    }
    return data as Content[];
};

/**
 * Finds all published content from a specific list of creator IDs, with pagination.
 * @param creatorIds - An array of creator UUIDs.
 * @param options - An object for pagination (limit, offset).
 * @returns An array of content objects, joined with creator profile data.
 */
export const findContentByCreatorIds = async (creatorIds: string[], options: { limit: number; offset: number }): Promise<any[] | null> => {
    if (creatorIds.length === 0) {
        return [];
    }

    const { data, error } = await supabase
        .from('content')
        .select(`
            *,
            creator: creator_id (*)
        `)
        .in('creator_id', creatorIds)
        .eq('status', 'published')
        // --- THIS IS THE CRITICAL FIX ---
        // Exclude 'unlisted' content from any feed generated by this function.
        .in('visibility', ['subscribers_only', 'pay_per_view'])
        // --- END OF FIX ---
        .order('created_at', { ascending: false })
        .range(options.offset, options.offset + options.limit - 1);

    if (error) {
        console.error('Error finding content by creator IDs:', error.message);
        return null;
    }
    return data;
};

/**
 * Finds a limited number of the most recent published content pieces for a specific creator.
 * @param creatorId - The UUID of the creator.
 * @param limit - The maximum number of content pieces to return.
 * @returns An array of content objects.
 */
export const findRecentContentByCreator = async (creatorId: string, limit: number): Promise<Content[] | null> => {
    const { data, error } = await supabase
        .from('content')
        .select('*')
        .eq('creator_id', creatorId)
        .eq('status', 'published') // Only show published content
        .order('created_at', { ascending: false })
        .limit(limit);

    if (error) {
        console.error(`Error finding recent content for creator ${creatorId}:`, error.message);
        return null;
    }
    return data.map(item => {
        const { id, ...rest } = item;
        return { ...rest, _id: id.toString() } as Content;
    });
};

/**
 * Finds a limited number of RECENT AND PUBLIC content pieces for a creator's profile.
 * @param creatorId - The UUID of the creator.
 * @param limit - The maximum number of content pieces to return.
 * @returns An array of content objects.
 */
export const findPublicContentByCreator = async (creatorId: string, limit: number): Promise<Content[] | null> => {
    const { data, error } = await supabase
        .from('content')
        .select('*')
        .eq('creator_id', creatorId)
        .eq('status', 'published')
        // --- THIS IS THE CRITICAL ADDITION ---
        // Only select content intended for the public feed.
        .in('visibility', ['subscribers_only', 'pay_per_view'])
        // --- END OF ADDITION ---
        .order('created_at', { ascending: false })
        .limit(limit);

    if (error) {
        console.error(`Error finding public content for creator ${creatorId}:`, error.message);
        return null;
    }
    return data.map(item => ({ ...item, _id: item.id.toString() } as Content));
};

/**
 * Calculates the sum of all views for a creator's content.
 * @param creatorId - The UUID of the creator.
 * @returns The total number of views.
 */
export const sumCreatorContentViews = async (creatorId: string): Promise<number> => {
    const { data, error } = await supabase
        .from('content')
        .select('stats')
        .eq('creator_id', creatorId);

    if (error) {
        console.error('Error summing content views:', error.message);
        return 0;
    }

    // The 'stats' column is JSON, so we need to access the 'views' property
    return data.reduce((sum, item) => sum + (item.stats?.views || 0), 0);
};

/**
 * Updates a piece of content in the database.
 * @param id - The ID of the content to update.
 * @param updates - An object containing the fields to update.
 * @returns The updated content object.
 */
export const updateContent = async (id: string, updates: Partial<Content>): Promise<Content | null> => {
    const { data, error } = await supabase
        .from('content')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

    if (error) {
        console.error('Error updating content:', error.message);
        return null;
    }
    return data as Content;
};

/**
 * Deletes a piece of content from the database.
 * Note: This does not delete the associated files from storage.
 * That should be handled in a service layer.
 * @param id - The ID of the content to delete.
 * @returns The deleted content object.
 */
export const deleteContent = async (id: string): Promise<Content | null> => {
    const { data, error } = await supabase
        .from('content')
        .delete()
        .eq('id', id)
        .select()
        .single();

    if (error) {
        console.error('Error deleting content:', error.message);
        return null;
    }
    return data as Content;
};
