/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as poDmPaymentProtocolSol from "./PoDMPaymentProtocol.sol";
export type { poDmPaymentProtocolSol };
export type { MockUSDC } from "./MockUSDC";
