import fs from 'fs';
import path from 'path';
import { Interface, ethers } from 'ethers';

function main() {
    const artifactPath = path.resolve(__dirname, '../contracts/artifacts/contracts/PoDMPaymentProtocol.sol/PoDMPaymentProtocol.json');
    if (!fs.existsSync(artifactPath)) {
        console.error(`Artifact not found at ${artifactPath}. Run 'npx hardhat compile' inside contracts/ directory first.`);
        process.exit(1);
    }

    const artifactJson = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
    const iface = new Interface(artifactJson.abi);

    // Compute function selectors

    const selectors = {
        paySubscription: iface.getFunction('paySubscription(address,address,uint256,bytes32,address,uint256)')!.selector,
        payTip: iface.getFunction('payTip(address,address,uint256,address,uint256)')!.selector,
        payPPV: iface.getFunction('payPPV(address,address,uint256,bytes32,address,uint256)')!.selector,
        processRenewal: iface.getFunction('processRenewal(address,address,address,uint256,address,uint256)')!.selector,
        processPayout: iface.getFunction('processPayout(address,address,uint256)')!.selector,
    };

    // Standard ERC-20 selectors
    const erc20Iface = new Interface([
        'function approve(address spender, uint256 amount) returns (bool)',
        'function allowance(address owner, address spender) view returns (uint256)'
    ]);
    const erc20Selectors = {
        approve: erc20Iface.getFunction('approve')!.selector,
        allowance: erc20Iface.getFunction('allowance')!.selector,
    };

    // Event topics
    const subPaidEvent = iface.getEvent('SubscriptionPaid');
    const tipPaidEvent = iface.getEvent('TipPaid');
    const ppvPaidEvent = iface.getEvent('PPVPaid');

    if (!subPaidEvent || !tipPaidEvent || !ppvPaidEvent) {
        console.error('One or more required events missing from contract ABI!');
        process.exit(1);
    }

    const eventTopics = {
        SubscriptionPaid: subPaidEvent.topicHash,
        TipPaid: tipPaidEvent.topicHash,
        PPVPaid: ppvPaidEvent.topicHash,
    };

    const requiredSignatures: Record<string, string> = {
        paySubscription: 'paySubscription(address,address,uint256,bytes32,address,uint256)',
        payTip: 'payTip(address,address,uint256,address,uint256)',
        payPPV: 'payPPV(address,address,uint256,bytes32,address,uint256)',
        processRenewal: 'processRenewal(address,address,address,uint256,address,uint256)',
        processPayout: 'processPayout(address,address,uint256)',
    };

    for (const [name, sig] of Object.entries(requiredSignatures)) {
        const fn = iface.getFunction(sig);
        if (!fn) {
            console.error(`Contract ABI is missing expected signature: ${sig} (${name})`);
            process.exit(1);
        }
    }

    // Derive human-readable ABI strings from the artifact itself so the emitted
    // module can never drift from the compiled contract.
    const humanReadableAbi = [
        `function ${iface.getFunction('paySubscription(address,address,uint256,bytes32,address,uint256)')!.format('sighash')}`,
        `function ${iface.getFunction('payTip(address,address,uint256,address,uint256)')!.format('sighash')}`,
        `function ${iface.getFunction('payPPV(address,address,uint256,bytes32,address,uint256)')!.format('sighash')}`,
        `function ${iface.getFunction('processRenewal(address,address,address,uint256,address,uint256)')!.format('sighash')}`,
        `function ${iface.getFunction('processPayout(address,address,uint256)')!.format('sighash')}`,
    ];

    const erc20HumanReadableAbi = [
        "function approve(address spender, uint256 amount) returns (bool)",
        "function allowance(address owner, address spender) view returns (uint256)"
    ];

    const fileContent = `// Auto-generated contract configuration and helper module.
// DO NOT EDIT DIRECTLY. Generated by scripts/generateContractConfig.ts

export const PODM_CONTRACT_ABI = ${JSON.stringify(humanReadableAbi, null, 4)} as const;

export const ERC20_ABI = ${JSON.stringify(erc20HumanReadableAbi, null, 4)} as const;

export const FUNCTION_SELECTORS = ${JSON.stringify(selectors, null, 4)} as const;

export const ERC20_SELECTORS = ${JSON.stringify(erc20Selectors, null, 4)} as const;

export const EVENT_TOPICS = ${JSON.stringify(eventTopics, null, 4)} as const;
`;

    const outputPath = path.resolve(__dirname, '../common/contractConfig.ts');
    fs.writeFileSync(outputPath, fileContent, 'utf8');
    console.log(`Successfully generated ${outputPath}`);
}

main();
