import fs from 'fs';
import path from 'path';
import { Interface, ethers } from 'ethers';

function main() {
    const artifactPath = path.resolve(__dirname, '../contracts/artifacts/contracts/PoDMPaymentProtocol.sol/PoDMPaymentProtocol.json');
    if (!fs.existsSync(artifactPath)) {
        console.error(`Artifact not found at ${artifactPath}. Run 'npx hardhat compile' inside contracts/ directory first.`);
        process.exit(1);
    }

    const artifactJson = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
    const iface = new Interface(artifactJson.abi);

    // Compute function selectors
    const paySubFunc = iface.getFunction('paySubscription');
    const payTipFunc = iface.getFunction('payTip');
    const payPPVFunc = iface.getFunction('payPPV');
    const processRenewalFunc = iface.getFunction('processRenewal');
    const processPayoutFunc = iface.getFunction('processPayout');

    if (!paySubFunc || !payTipFunc || !payPPVFunc || !processRenewalFunc || !processPayoutFunc) {
        console.error('One or more required functions missing from contract ABI!');
        process.exit(1);
    }

    const selectors = {
        paySubscription: paySubFunc.selector,
        payTip: payTipFunc.selector,
        payPPV: payPPVFunc.selector,
        processRenewal: processRenewalFunc.selector,
        processPayout: processPayoutFunc.selector,
    };

    // Standard ERC-20 selectors
    const erc20Iface = new Interface([
        'function approve(address spender, uint256 amount) returns (bool)',
        'function allowance(address owner, address spender) view returns (uint256)'
    ]);
    const erc20Selectors = {
        approve: erc20Iface.getFunction('approve')!.selector,
        allowance: erc20Iface.getFunction('allowance')!.selector,
    };

    // Event topics
    const subPaidEvent = iface.getEvent('SubscriptionPaid');
    const tipPaidEvent = iface.getEvent('TipPaid');
    const ppvPaidEvent = iface.getEvent('PPVPaid');

    if (!subPaidEvent || !tipPaidEvent || !ppvPaidEvent) {
        console.error('One or more required events missing from contract ABI!');
        process.exit(1);
    }

    const eventTopics = {
        SubscriptionPaid: subPaidEvent.topicHash,
        TipPaid: tipPaidEvent.topicHash,
        PPVPaid: ppvPaidEvent.topicHash,
    };

    const humanReadableAbi = [
        "function paySubscription(address tokenAddress, address creator, uint256 amount, bytes32 tierIdHash, address referrer, uint256 customPlatformFeeBps)",
        "function payTip(address tokenAddress, address creator, uint256 amount, address referrer, uint256 customPlatformFeeBps)",
        "function payPPV(address tokenAddress, address creator, uint256 amount, bytes32 contentIdHash, address referrer, uint256 customPlatformFeeBps)",
        "function processRenewal(address tokenAddress, address fan, address creator, uint256 amount, address referrer, uint256 customPlatformFeeBps)",
        "function processPayout(address creator, uint256 amount)"
    ];

    const erc20HumanReadableAbi = [
        "function approve(address spender, uint256 amount) returns (bool)",
        "function allowance(address owner, address spender) view returns (uint256)"
    ];

    const fileContent = `// Auto-generated contract configuration and helper module.
// DO NOT EDIT DIRECTLY. Generated by scripts/generateContractConfig.ts

export const PODM_CONTRACT_ABI = ${JSON.stringify(humanReadableAbi, null, 4)} as const;

export const ERC20_ABI = ${JSON.stringify(erc20HumanReadableAbi, null, 4)} as const;

export const FUNCTION_SELECTORS = ${JSON.stringify(selectors, null, 4)} as const;

export const ERC20_SELECTORS = ${JSON.stringify(erc20Selectors, null, 4)} as const;

export const EVENT_TOPICS = ${JSON.stringify(eventTopics, null, 4)} as const;
`;

    const outputPath = path.resolve(__dirname, '../common/contractConfig.ts');
    fs.writeFileSync(outputPath, fileContent, 'utf8');
    console.log(`Successfully generated ${outputPath}`);
}

main();
