name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./PoDM_project

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ./PoDM_project/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
      env:
        CI: true

  frontend-build-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./podm-frontend

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ./podm-frontend/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build
